name: build-and-deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install dependencies
              run: npm install
            - name: Generate build
              run: npm run build
            - name: Share artifact inside workflow
              uses: actions/upload-artifact@v1
              with:
                  name: react-github-actions-build
                  path: build
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Get artifact
              uses: actions/download-artifact@v1
              with:
                  name: react-github-actions-build
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            - name: Deploy to S3
              run: aws s3 sync . s3://margaritagubanova.com --acl public-read
              working-directory: react-github-actions-build
